### PR TITLE
added support for swagger UI config file

### PR DESCRIPTION
**Pull request by oliver-orchestra**
Following up on https://github.com/harmbandstra/swagger-ui-bundle/issues/21 here's a first take on this. Please have a look and let me know if that makes sense.

The regular expression against the `index.html` isn't ideal, but I think it's probably still the best way to make it work even with upstream changes.
I wasn't able to move all the config to the config file, e.g. layout and presets, seems these need to be in the actual file to work - the configFile is loaded too late for it to work I guess.

### CODE REVIEW

**Comment by harmbandstra** [comment]
Hi Oliver, thanks for the PR. I agree the regex isn't ideal. Why not just pass the config file on the URL?

If I expose the config.json in the `hb_swagger_ui.files` config (just to test), I can use the configuration with this url. Seems to work :-)
https://127.0.0.1:8000/docs/?url=/docs/file/petstore.yaml&configUrl=/docs/file/config.json

**Comment by oliver-orchestra** [comment]
Good point - initially I wanted to replace the whole config, but it seems that's not possible with the configUrl, and I don't need to change the layout or plugins, so this should be simpler.
Does it make more sense now?

**Comment by harmbandstra** [comment]
Hi Oliver, that looks a lot more like what I had in mind :-) There are some small things, I would like to change. I have some time tomorrow to get those fixed and get it merged asap.

**Comment by harmbandstra** [comment]
Hi @oliver-orchestra, finally got it merged! It's in release 4.5.0. Let me know if you run into any issues.

**Pull request merged**
